name: Deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@v1
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: |
          swift build -c release --arch x86_64 --arch arm64
          mv `swift build -c release --arch x86_64 --arch arm64 --show-bin-path`/torino torino
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: torino