name: Run tests
on: 
  push:
    paths:
      - Sources/**
      - Tests/**
      - .github/**
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/**
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: AckeeCZ/load-xcode-version@1.0.1
    - uses: actions/cache@v3.3.1
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Run tests
      run: swift test
