name: Run tests
on: 
  push:
    paths:
      - Sources/**
      - Tests/**
  pull_request:
    paths:
      - Sources/**
      - Tests/**
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
